### ISSUE TITLE
Make it compatible with electrolysis

### ISSUE THREAD

**Issue by moimael** [mkiol/GNotifier#144] opened 2016-09-23 11:22 UTC
Hi,

e10s start to be deployed to more and more people, and this addon is marked as not compatible with it.
Could you check if this is easily feasible ? From what I see it might need some work to port it to WebExtensions.

https://compatibility-lookup.services.mozilla.com/
https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

Thanks.

**Comment by mkiol** [comment] 2016-09-23 14:09
Thank you for bringing this up. I didn't notice any issues related to multiprocess, so upcoming new version will be marked as "compatible". You right, GNotifier uses some low-level and XPCOM apis, but unfortunately, it seems that it doesn't cause any incompatibilities with electrolysis.

[duplicate of #133]

**Comment by mkiol** [comment] 2016-10-01 16:08
Latest release is marked as "compatible". If you find any problems related to electrolysis please reopen this issue.

**Closed by mkiol** 2016-10-01 16:08 UTC
Labels: duplicate
