### ISSUE TITLE
GNOME Shell sometimes restarts

### ISSUE THREAD

**Issue by d9h02f** [mkiol/GNotifier#59] opened 2015-06-27 17:32 UTC
Sometimes when a Firefox notification is shown, the GNOME Shell freezes for a couple of seconds and then restarts. This seems to happen mostly (or only) when it's a notification for a completed download, and at that time another notification (from another application) also wants to show up.

I'm not sure if this extension is the cause, but it seems like this always happens right when it shows a Firefox notification and another notification, and I currently only use two shell extensions, so I think there is at least a relation somehow.

**Comment by mkiol** [comment] 2015-06-28 10:33
Thanks for the report. Will look into that.

**Comment by mkiol** [comment] 2015-07-26 16:15
Here is new [release](https://github.com/mkiol/GNotifier/raw/master/gnotifier-1.9.0-pre6.xpi). I did many changes in libnotify handling. Now, it should be more stable, so I really hope the crashing issue is fixed.

**Comment by d9h02f** [comment] 2015-07-27 10:21
I'll try it out for a while and see if I run into the problem again. So far so good.

**Comment by bmillemathias** [comment] 2015-10-08 18:13
Hello @d9h02f,

Did you have chance to test the latest release and check that fix the issue ?

Thanks

**Comment by d9h02f** [comment] 2015-10-09 08:35
Unfortunately the issue doesn't seem to be fixed, but it seems like it might actually be an issue with GNOME Shell, as I've now also had it happen with Geary notifications.

**Comment by auipga** [comment] 2015-11-19 13:32
I ran into this kind of problem too. Gnome Shell freezes for almost 2 minutes.
Sometimes the reason is the "completed download" notification, but more often caused by those by web.whatsapp.com.

**Comment by mkiol** [comment] 2015-11-20 08:20
@auipga so, you ran into "freeze" problem using 1.8.x version? Right? Since version 1.9.x an issue should be fixed.

**Comment by d9h02f** [comment] 2015-11-23 12:32
Closing this as it turns out it is/was a GNOME bug, fixed in 3.18.1, maybe backported to 3.16.4 but I didn't check yet. We blamed this extension by mistake!

https://bugzilla.gnome.org/show_bug.cgi?id=749656

**Comment by mkiol** [comment] 2015-11-23 13:59
Great! So, closing this issue.

**Closed by mkiol** 2015-11-23 13:59 UTC

**Comment by d9h02f** [comment] 2015-11-23 18:52
Ha, oops, forgot to actually close. Thanks.
