### ISSUE TITLE
Notifications doesn't work

### ISSUE THREAD

**Issue by Limdel** [mkiol/GNotifier#87] opened 2016-02-17 21:37 UTC
I'm running Firefox Aurora 46.0a2, libnotify-id and Dunst notification manager. I can receive FF notifications, not native though, like chrome's, but when I enable GNotifier I can't receive any notifications at all. if I'm not mistaken, one time when I disabled extension and wanted to test notifications, first notification came out as native one.

**Comment by mkiol** [comment] 2016-02-19 13:32
Thank for the report. Yes, I can confirm it doesn't work. 

Even without GNotifier, FF46 behaves quite unstable. Some notification are native (via built-in integration, not GNotifier) and some are not. You can distinguish because GNotifier's notification has "Open" as a name for default action and built-in notification are using "Activate" as a label. 

It seems to be bug inside FF, similar to #80. Most of bugs are fixed in beta release, so in my opinion we should wait and check beta release.

**Closed** 2016-03-23 19:28 UTC
