### ISSUE TITLE
Indicator pops up again after clicking download icon

### ISSUE THREAD

**Issue by aibaraiduas** [mkiol/GNotifier#56] opened 2015-05-31 19:51 UTC
When I finish downloading a file with Firefox GNotifier correctly pops up a message saying the download is complete. But if I click on the blue-colored download icon in Firefox later it pops up the message again. If I delete or move the file I can even get it to pop up a third time. It used to properly only display once. 

I'm using GNotifier 1.8.9.1-signed with Firefox 38 on Ubuntu 14.04 (Unity).

**Comment by mkiol** [comment] 2015-06-06 10:34
Thank you for the report. Can you give me more details? Maybe screenshot? I've tried to reproduce scenario you've described and everything seems to be fine. "Download complete" appears only once. Tested on fresh Ubuntu 14.04 installation with FF38 and GNotifier 1.8.91.

**Comment by aibaraiduas** [comment] 2015-06-07 15:58
Here are two screenshots. The first is when I downloaded your avatar icon: the download complete message pops up and goes away. Once it was gone I deleted the file, then clicked on the download icon: the message then appeared again.

![screenshot from 2015-06-07 11 51 59](https://cloud.githubusercontent.com/assets/5825551/8024733/0e465538-0d0c-11e5-87ae-949f67db29ce.png)
![screenshot from 2015-06-07 11 52 24](https://cloud.githubusercontent.com/assets/5825551/8024735/11781ce6-0d0c-11e5-8ca7-b3acd4558404.png)

I've also had it where after downloading a file, even when it hasn't been moved or deleted, as soon as I click the download arrow icon a message will appear, then appear a third time when the file is moved or deleted.

Maybe it's just something weird with my system? I'll try messing around with a fresh Firefox profile and various addons.

**Comment by aibaraiduas** [comment] 2015-06-07 16:15
I just tested a new Firefox profile with GNotifier as the only add-on. The bug still occurred. Weird that you couldn't reproduce it.

**Comment by aibaraiduas** [comment] 2015-06-07 19:38
I tried some older versions of GNotifier that were released last year. I know this bug didn't occur until fairly recently, yet with the older versions of GNotifier on Firefox 38 it still does.

I also tested with older versions of Firefox. Version 37 and earlier function just fine, so it's a problem specific to GNotifier and FF 38. I also tested with FF38 downloaded directly from Mozilla (not the version in Ubuntu's repositories) just in case it would be different, but, no, I still got the error. That doesn't explain why you couldn't reproduce the problem on the same setup...

**Comment by aibaraiduas** [comment] 2015-06-07 20:56
And one final bit of information:
Once multiple files are downloaded then deleted or moved, if the download icon is clicked only messages about the three files displayed there will pop up. However, if the download library is opened to view the others, every time one is clicked its message will pop up again. 

See this screenshot, where a message concerning a file that finished downloading over 10 minutes before pops up when the file in the library window is clicked:
![screenshot from 2015-06-07 16 49 13](https://cloud.githubusercontent.com/assets/5825551/8026022/00adde4e-0d36-11e5-8864-980036299e94.png)

**Comment by mkiol** [comment] 2015-06-08 19:43
Ok, I've reproduce the behavior. I am sorry, I didn't catch that *deleting* files is crucial to see this bug. It is very very weird...

**Comment by mkiol** [comment] 2015-06-09 08:20
I made some debugging yesterday and my conclusion is that it have to be bug in FF (precisely in Downloads.jsm module). Additional "download succeeded" event is triggered and I have no clue why. 

I can implement workaround based on check if downloaded file exists. If yes, notification will be shown, if not, will be blocked.

**Comment by mkiol** [comment] 2015-07-04 15:53
Here is [new release](https://github.com/mkiol/GNotifier/raw/master/gnotifier-1.9.0-pre3.xpi). Bug should be fixed. @aibaraiduas I would be very grateful if you could test it and give me feedback.

**Closed** 2015-11-21 14:28 UTC
